## auto generated from commands_def.h

CMD_TYPE_RESET = 0
CMD_TYPE_UART = 1
CMD_TYPE_I2C = 2
CMD_TYPE_SPI = 3
CMD_TYPE_PIO = 4
CMD_TYPE_LED = 5
CMD_TYPE_LCD = 6
CMD_TYPE_BTN = 7
CMD_TYPE_ADC = 8
CMD_TYPE_DAC = 9


CMD_RESP_NULL = 0
CMD_RESP_RESET = 1
CMD_RESP_OK = 2
CMD_RESP_INVALID_CMD = 3
CMD_RESP_OVERFLOW = 4
CMD_RESP_CRC_ERR = 5

